//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlangHub.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KlangHub.Core.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffering.
        /// </summary>
        public static string Buffering {
            get {
                return ResourceManager.GetString("Buffering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Log.
        /// </summary>
        public static string Button_ClearLog_Text {
            get {
                return ResourceManager.GetString("Button_ClearLog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string Button_ClipboardCopy_Text {
            get {
                return ResourceManager.GetString("Button_ClipboardCopy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string Button_Down_Text {
            get {
                return ResourceManager.GetString("Button_Down_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        public static string Button_Mute_Text {
            get {
                return ResourceManager.GetString("Button_Mute_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Settings.
        /// </summary>
        public static string Button_ResetSetting_Text {
            get {
                return ResourceManager.GetString("Button_ResetSetting_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan again for devices.
        /// </summary>
        public static string Button_ScanAgain_Text {
            get {
                return ResourceManager.GetString("Button_ScanAgain_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Devices.
        /// </summary>
        public static string Button_SyncDevices_Text {
            get {
                return ResourceManager.GetString("Button_SyncDevices_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string Button_Up_Text {
            get {
                return ResourceManager.GetString("Button_Up_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically restart when the stream is closed.
        /// </summary>
        public static string Check_AutomaticallyRestart_Text {
            get {
                return ResourceManager.GetString("Check_AutomaticallyRestart_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically start devices at startup.
        /// </summary>
        public static string Check_AutomaticallyStart_Text {
            get {
                return ResourceManager.GetString("Check_AutomaticallyStart_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-mute/unmute desktop audio.
        /// </summary>
        public static string Check_AutoMute_Text {
            get {
                return ResourceManager.GetString("Check_AutoMute_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically start last used devices and groups at startup.
        /// </summary>
        public static string Check_AutonaticallyStartLastUsed_Text {
            get {
                return ResourceManager.GetString("Check_AutonaticallyStartLastUsed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert multi-channel audio to stereo output.
        /// </summary>
        public static string Check_ConvertMultiChannelToStereo_Text {
            get {
                return ResourceManager.GetString("Check_ConvertMultiChannelToStereo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark mode.
        /// </summary>
        public static string Check_DarkMode_Text {
            get {
                return ResourceManager.GetString("Check_DarkMode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Keyboard shortcuts: Up = Ctrl+Alt+U; Down = Ctrl+Alt+D; (Un)Mute = Ctrl+Alt+M.
        /// </summary>
        public static string Check_KeyboardShortcuts_Text {
            get {
                return ResourceManager.GetString("Check_KeyboardShortcuts_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log device communication.
        /// </summary>
        public static string Check_LogDeviceCommunication_Text {
            get {
                return ResourceManager.GetString("Check_LogDeviceCommunication_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to systray when closing.
        /// </summary>
        public static string Check_MinimizeToTray_Text {
            get {
                return ResourceManager.GetString("Check_MinimizeToTray_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show lag control (experimental).
        /// </summary>
        public static string Check_ShowLagControl_Text {
            get {
                return ResourceManager.GetString("Check_ShowLagControl_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show window at startup.
        /// </summary>
        public static string Check_ShowWindowOnStart_Text {
            get {
                return ResourceManager.GetString("Check_ShowWindowOnStart_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start application when Windows starts.
        /// </summary>
        public static string Check_StartApplicationWhenWindowsStarts_Text {
            get {
                return ResourceManager.GetString("Check_StartApplicationWhenWindowsStarts_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop Audio Streamer.
        /// </summary>
        public static string ChromeCast_StreamTitle {
            get {
                return ResourceManager.GetString("ChromeCast_StreamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Error.
        /// </summary>
        public static string ConnectError {
            get {
                return ResourceManager.GetString("ConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices only.
        /// </summary>
        public static string DevicesOnly {
            get {
                return ResourceManager.GetString("DevicesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposed.
        /// </summary>
        public static string Disposed {
            get {
                return ResourceManager.GetString("Disposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices (click name to start streaming).
        /// </summary>
        public static string Group_Devices_Text {
            get {
                return ResourceManager.GetString("Group_Devices_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lag Control.
        /// </summary>
        public static string Group_Lag_Text {
            get {
                return ResourceManager.GetString("Group_Lag_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Group_Options_Text {
            get {
                return ResourceManager.GetString("Group_Options_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume all devices:.
        /// </summary>
        public static string Group_VolumeAllDevices_Text {
            get {
                return ResourceManager.GetString("Group_VolumeAllDevices_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups only.
        /// </summary>
        public static string GroupsOnly {
            get {
                return ResourceManager.GetString("GroupsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string Idle {
            get {
                return ResourceManager.GetString("Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Request.
        /// </summary>
        public static string InvalidRequest {
            get {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device buffer (in seconds).
        /// </summary>
        public static string Label_BufferInSeconds_Text {
            get {
                return ResourceManager.GetString("Label_BufferInSeconds_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter devices.
        /// </summary>
        public static string Label_FilterDevices_Text {
            get {
                return ResourceManager.GetString("Label_FilterDevices_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP4 address used:.
        /// </summary>
        public static string Label_IPAddressUsed_Text {
            get {
                return ResourceManager.GetString("Label_IPAddressUsed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest keep-alive message:.
        /// </summary>
        public static string Label_KeepAlive_Text {
            get {
                return ResourceManager.GetString("Label_KeepAlive_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental feature: Try to keep the buffer on the device as small as possible without hearing dropouts..
        /// </summary>
        public static string Label_LagExperimental_Text {
            get {
                return ResourceManager.GetString("Label_LagExperimental_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Label_Language_Text {
            get {
                return ResourceManager.GetString("Label_Language_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about options on Github.
        /// </summary>
        public static string Label_LinkHelp_Text {
            get {
                return ResourceManager.GetString("Label_LinkHelp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum lag / best quality.
        /// </summary>
        public static string Label_MaximumLag_Text {
            get {
                return ResourceManager.GetString("Label_MaximumLag_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minimum lag / poor quality.
        /// </summary>
        public static string Label_MinimumLag_Text {
            get {
                return ResourceManager.GetString("Label_MinimumLag_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available on Github.
        /// </summary>
        public static string Label_NewVersionAvailable {
            get {
                return ResourceManager.GetString("Label_NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording device:.
        /// </summary>
        public static string Label_RecordingDevice_Text {
            get {
                return ResourceManager.GetString("Label_RecordingDevice_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream format.
        /// </summary>
        public static string Label_StreamFormat_Text {
            get {
                return ResourceManager.GetString("Label_StreamFormat_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mp3 formats have a long lag and buffering time..
        /// </summary>
        public static string Label_StreamFormatExtra_Text {
            get {
                return ResourceManager.GetString("Label_StreamFormatExtra_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string Language_French {
            get {
                return ResourceManager.GetString("Language_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launched Application.
        /// </summary>
        public static string LaunchedApplication {
            get {
                return ResourceManager.GetString("LaunchedApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching Application.
        /// </summary>
        public static string LaunchingApplication {
            get {
                return ResourceManager.GetString("LaunchingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Cancelled.
        /// </summary>
        public static string LoadCancelled {
            get {
                return ResourceManager.GetString("LoadCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Failed.
        /// </summary>
        public static string LoadFailed {
            get {
                return ResourceManager.GetString("LoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Media.
        /// </summary>
        public static string LoadingMedia {
            get {
                return ResourceManager.GetString("LoadingMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Firewall &amp; Wi-Fi Privacy Status.
        /// </summary>
        public static string LoadingMediaCheckFirewall {
            get {
                return ResourceManager.GetString("LoadingMediaCheckFirewall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string Log_In {
            get {
                return ResourceManager.GetString("Log_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to out.
        /// </summary>
        public static string Log_Out {
            get {
                return ResourceManager.GetString("Log_Out", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Live from your PC.
        /// </summary>
        public static string Media_Subtitle {
            get {
                return ResourceManager.GetString("Media_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Desktop Audio Streamer.
        /// </summary>
        public static string MainForm_Text {
            get {
                return ResourceManager.GetString("MainForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No IP addresses found on your device..
        /// </summary>
        public static string MessageBox_NoIPAddress {
            get {
                return ResourceManager.GetString("MessageBox_NoIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recording devices found..
        /// </summary>
        public static string MessageBox_NoRecordingDevices {
            get {
                return ResourceManager.GetString("MessageBox_NoRecordingDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mp3 (128 kbps).
        /// </summary>
        public static string Mp3_128 {
            get {
                return ResourceManager.GetString("Mp3_128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mp3 (320 kbps).
        /// </summary>
        public static string Mp3_320 {
            get {
                return ResourceManager.GetString("Mp3_320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected.
        /// </summary>
        public static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        public static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing.
        /// </summary>
        public static string Playing {
            get {
                return ResourceManager.GetString("Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Tab_Log_Text {
            get {
                return ResourceManager.GetString("Tab_Log_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string Tab_Main_Text {
            get {
                return ResourceManager.GetString("Tab_Main_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Tab_Options_Text {
            get {
                return ResourceManager.GetString("Tab_Options_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Tooltip_Group_Text {
            get {
                return ResourceManager.GetString("Tooltip_Group_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording level.
        /// </summary>
        public static string Tooltip_RecordingLevel_Text {
            get {
                return ResourceManager.GetString("Tooltip_RecordingLevel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string TrayIcon_Close {
            get {
                return ResourceManager.GetString("TrayIcon_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wav (44100 Hz/16bit).
        /// </summary>
        public static string Wav {
            get {
                return ResourceManager.GetString("Wav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wav (Soundcard&apos;s sample rate/16bit).
        /// </summary>
        public static string Wav_16bit {
            get {
                return ResourceManager.GetString("Wav_16bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wav (Soundcard&apos;s sample rate/24bit).
        /// </summary>
        public static string Wav_24bit {
            get {
                return ResourceManager.GetString("Wav_24bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wav (Soundcard&apos;s sample rate/32bit).
        /// </summary>
        public static string Wav_32bit {
            get {
                return ResourceManager.GetString("Wav_32bit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The mp3 formats have a long lag and buffering time..
        /// </summary>
        public static string Label_StreamTitle_Text
        {
            get
            {
                return ResourceManager.GetString("Label_StreamTitle_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Made with ♥ by Neo & Trinity — 2026.
        /// </summary>
        public static string Label_Credit_Text
        {
            get
            {
                return ResourceManager.GetString("Label_Credit_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SOUND PROFILE &amp; CONNECTION.
        /// </summary>
        public static string Label_Section_Sound_Text
        {
            get
            {
                return ResourceManager.GetString("Label_Section_Sound_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BEHAVIOR &amp; COMFORT.
        /// </summary>
        public static string Label_Section_Behavior_Text
        {
            get
            {
                return ResourceManager.GetString("Label_Section_Behavior_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} · streaming to your whole home.
        /// </summary>
        public static string Label_RoomSummarySubtitle_Text
        {
            get
            {
                return ResourceManager.GetString("Label_RoomSummarySubtitle_Text", resourceCulture);
            }
        }

        public static string Label_RoomSummaryTitle_Text
        {
            get
            {
                return ResourceManager.GetString("Label_RoomSummaryTitle_Text", resourceCulture);
            }
        }

        public static string Label_RoomSummaryPlayingOne_Text
        {
            get
            {
                return ResourceManager.GetString("Label_RoomSummaryPlayingOne_Text", resourceCulture);
            }
        }

        public static string Label_RoomSummaryPlayingMany_Text
        {
            get
            {
                return ResourceManager.GetString("Label_RoomSummaryPlayingMany_Text", resourceCulture);
            }
        }

        public static string Label_RoomSummaryDevicesOne_Text
        {
            get
            {
                return ResourceManager.GetString("Label_RoomSummaryDevicesOne_Text", resourceCulture);
            }
        }

        public static string Label_RoomSummaryDevicesMany_Text
        {
            get
            {
                return ResourceManager.GetString("Label_RoomSummaryDevicesMany_Text", resourceCulture);
            }
        }

        public static string Label_RoomSummaryGroupsOne_Text
        {
            get
            {
                return ResourceManager.GetString("Label_RoomSummaryGroupsOne_Text", resourceCulture);
            }
        }

        public static string Label_RoomSummaryGroupsMany_Text
        {
            get
            {
                return ResourceManager.GetString("Label_RoomSummaryGroupsMany_Text", resourceCulture);
            }
        }

        public static string Label_RoomSummaryLossless_Text
        {
            get
            {
                return ResourceManager.GetString("Label_RoomSummaryLossless_Text", resourceCulture);
            }
        }

        public static string Label_RoomSummaryCompressed_Text
        {
            get
            {
                return ResourceManager.GetString("Label_RoomSummaryCompressed_Text", resourceCulture);
            }
        }

        public static string Label_RoomSummaryEmpty_Text
        {
            get
            {
                return ResourceManager.GetString("Label_RoomSummaryEmpty_Text", resourceCulture);
            }
        }

        public static string Card_Subtitle_Group_Text
        {
            get
            {
                return ResourceManager.GetString("Card_Subtitle_Group_Text", resourceCulture);
            }
        }

        public static string Card_Subtitle_Device_Text
        {
            get
            {
                return ResourceManager.GetString("Card_Subtitle_Device_Text", resourceCulture);
            }
        }

        public static string Card_Subtitle_GroupPlain_Text
        {
            get
            {
                return ResourceManager.GetString("Card_Subtitle_GroupPlain_Text", resourceCulture);
            }
        }

        public static string Card_Muted_Text
        {
            get
            {
                return ResourceManager.GetString("Card_Muted_Text", resourceCulture);
            }
        }

        public static string Popup_SpeakerOptions_Text
        {
            get
            {
                return ResourceManager.GetString("Popup_SpeakerOptions_Text", resourceCulture);
            }
        }

        public static string Popup_Room_Text
        {
            get
            {
                return ResourceManager.GetString("Popup_Room_Text", resourceCulture);
            }
        }

        public static string Popup_RoomHint_Text
        {
            get
            {
                return ResourceManager.GetString("Popup_RoomHint_Text", resourceCulture);
            }
        }

        public static string Popup_MaxVolume_Text
        {
            get
            {
                return ResourceManager.GetString("Popup_MaxVolume_Text", resourceCulture);
            }
        }

        public static string Popup_Done_Text
        {
            get
            {
                return ResourceManager.GetString("Popup_Done_Text", resourceCulture);
            }
        }

        public static string Artwork_Tagline_Text
        {
            get
            {
                return ResourceManager.GetString("Artwork_Tagline_Text", resourceCulture);
            }
        }

        public static string Room_Presets_Text
        {
            get
            {
                return ResourceManager.GetString("Room_Presets_Text", resourceCulture);
            }
        }

        public static string Room_Unassigned_Text
        {
            get
            {
                return ResourceManager.GetString("Room_Unassigned_Text", resourceCulture);
            }
        }

        public static string Button_GroupRooms_Text
        {
            get
            {
                return ResourceManager.GetString("Button_GroupRooms_Text", resourceCulture);
            }
        }

        public static string Room_SpeakersOne_Text
        {
            get
            {
                return ResourceManager.GetString("Room_SpeakersOne_Text", resourceCulture);
            }
        }

        public static string Room_SpeakersMany_Text
        {
            get
            {
                return ResourceManager.GetString("Room_SpeakersMany_Text", resourceCulture);
            }
        }

    }
}
